### ISSUE TITLE
RayStation bugs

### ISSUE THREAD

**Issue by ferdymercury** [mghro/rad-collision#15]
These have been reported to RaySearch:

**Comment by ferdymercury** [comment]
RayStation (10A) crashes when trying to create an ROI, if some ROIs or RTstruct or TPlan is locked or approved, with the trace:
`RaySearch.CoreUtilities.LogicalException: Exception was thrown by a business-event handler. Application must be taken down (RoiGeometries). ---> RaySearch.CoreUtilities.LogicalException: Producer threw an exception. Application must be taken down. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> RaySearch.CoreUtilities.LogicalException: A produced property on attached data can only be set by its producer. Produced data cannot be modified. Produced data on immutable objects cannot be reproduced after attaching (SupportGeometries).`

**Comment by ferdymercury** [comment]
RayStation (10A) crashes sometimes in the 3D viewer tab if you import STL geometries that are not closed surfaces, with the backtrace 'ComputeMeshIntersections failed'

```
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> RaySearch.CoreUtilities.LogicalException: ComputeMeshIntersections failed
   at RaySearch.CoreUtilities.DesignByContract.Assert.Fail(String message)
   at RaySearch.CoreServices.ImageProcessing.MeshIntersectionService.GetMeshIntersections(Point3`1[] triangleVertices, Int32[] triangleIndices, Point3`1[] pointsInPlanes, Point3`1 planeNormal, Boolean smoothContours, Double zEpsilon)
   at RaySearch.CorePlatform.Presentation.PatientViews.ShapeView.GetCutPlaneContoursFromMeshAsync_(IPlane plane, TriangleMesh mesh)
   at RaySearch.CorePlatform.Presentation.PatientViews.TriangleMeshView.<GetCutPlaneContoursAsync>d__3.MoveNext()
```

**Comment by ferdymercury** [comment]
RayStation (8B) crashes sometimes when calling GetCenterOfROI() to correctly center the Couch. For this reason we use instead now GetBoundingBox as a workaround.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at RaySearch.CoreServices.ImageProcessing.RoiContoursService.resolveOverlappingContours(vector<std::vector<RaySearch::LinAlgPoint3<double>\,std::allocator<RaySearch::LinAlgPoint3<double> > >\,std::allocator<std::vector<RaySearch::LinAlgPoint3<double>\,std::allocator<RaySearch::LinAlgPoint3<double> > > > >* , Double )
   at RaySearch.CoreServices.ImageProcessingAdapters.RoiContoursServiceAdapter.ResolveOverlappingContours(IReadOnlyList`1 contours, Double zEpsilon)
   at RaySearch.CorePlatform.Presentation.PatientViews.ContourPostProcessingUtils.GetNonSelfOverlappingContourSetData(IReadOnlyList`1 contours, IPlane plane, Double zTolerance)
   at RaySearch.CorePlatform.Presentation.PatientViews.ShapeConverter.GetRoiContourSet_(Shape shape, ImageStack imageStack, Plane plane)
   at RaySearch.CorePlatform.Presentation.PatientViews.ShapeConverter.GetBinaryRoi_(Shape shape, ImageStack imageStack, ComputeBinaryVolumeService computeBinaryVolumeService)
   at RaySearch.CorePlatform.Presentation.PatientViews.ShapeView.GetBinaryRoi_()
   at RaySearch.CoreUtilities.AsyncCache`1.<>c__DisplayClass10_0.<GetOrCreate>b__0(CancellationToken _)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by ferdymercury** [comment]
case 00050735

```
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Could not execute sql-command. ---> System.InvalidOperationException: SnappyStream is in broken state due to previous error
at RaySearch.Snappy.NET.SnappyStream.CheckStream()
at RaySearch.Snappy.NET.SnappyStream.EnsureCompressionMode()
at RaySearch.Snappy.NET.SnappyStream.Flush()
at RaySearch.Snappy.NET.SnappyStream.Dispose(Boolean disposing)
at System.IO.Stream.Close()
at RaySearch.CorePlatform.DataSources.Database.GenericDB.UndoRedo.UndoRedoDbDataStore.<>c__DisplayClass8_2.<Add>b__1()
at RaySearch.CorePlatform.DataSources.Database.GenericDB.HandleSqlErrorsContext.<>c__DisplayClass17_0.<Retry>b__0()
at RaySearch.CorePlatform.DataSources.Database.GenericDB.HandleSqlErrorsContext.<>c__DisplayClass18_0`1.<Retry>b__0()
at RaySearch.CorePlatform.DataSources.Database.GenericDB.HandleSqlErrorsContext.<RetryRec_>d__19`1.MoveNext()
```

This was solved in 9B I believe.

**Comment by ferdymercury** [comment]
RayStation (9A) sometimes crashes when calculating the DSC for complex STL geometries with holes, etc.

Case number 00050729

```
RaySearch.CoreUtilities.LogicalException: Unhandled exception re thrown, original stack is preserved in the InnerException property ---> System.AggregateException: An error occured while execute action Comparison of roi geometries ---> System.Runtime.InteropServices.SEHException: External component has thrown an exception.
at RaySearch.CoreServices.ImageProcessing.RoiContoursService.resolveOverlappingContours(vector<std::vector<RaySearch::LinAlgPoint3<double>\,std::allocator<RaySearch::LinAlgPoint3<double> > >\,std::allocator<std::vector<RaySearch::LinAlgPoint3<double>\,std::allocator<RaySearch::LinAlgPoint3<double> > > > >* , Double )
at RaySearch.CoreServices.ImageProcessingAdapters.RoiContoursServiceAdapter.ResolveOverlappingContours(IReadOnlyList`1 contours, Double zEpsilon)
at RaySearch.CorePlatform.Presentation.PatientViews.ContourPostProcessingUtils.GetNonSelfOverlappingContourSetData(IReadOnlyList`1 contours, IPlane plane, Double zTolerance)
at RaySearch.CorePlatform.Presentation.PatientViews.ShapeConverter.GetRoiContourSetSliceAligned(Shape shape, ImageStack imageStack, Boolean allowExtraSliceLocations)
at RaySearch.CorePlatform.Presentation.PatientViews.ShapeView.GetRoiContourSet_()
at RaySearch.CorePlatform.Presentation.PatientModeling.Actions.RoiActions.ComparisonOfRoiGeometriesAction.DoWork_()
at RaySearch.CorePlatform.Framework.Action.DoWorkSequence_()
at RaySearch.CorePlatform.Framework.ActionScheduler.Execute(SyncAction action, Boolean saveOnCompletion)
```

Workaround: simplify STL geometry.
